# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib winitRpackage, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}


`create_event_loop_on_main_thread` <- function() {
  .savvy_wrap_MainEventLoop(.Call(savvy_create_event_loop_on_main_thread__impl))
}


`run_event_loop_on_main_thread` <- function(`main_event_loop`) {
  `main_event_loop` <- .savvy_extract_ptr(`main_event_loop`, "MainEventLoop")
  invisible(.Call(savvy_run_event_loop_on_main_thread__impl, `main_event_loop`))
}


`run_event_loop_on_spawned_thread` <- function() {
  invisible(.Call(savvy_run_event_loop_on_spawned_thread__impl))
}

### wrapper functions for MainEventLoop


`.savvy_wrap_MainEventLoop` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- "MainEventLoop"
  e
}

#' @export
`$<-.MainEventLoop` <- function(x, name, value) stop("MainEventLoop cannot be modified", call. = FALSE)

#' @export
`[[<-.MainEventLoop` <- function(x, i, value) stop("MainEventLoop cannot be modified", call. = FALSE)



`MainEventLoop` <- new.env(parent = emptyenv())

#' @export
`$<-.MainEventLoop` <- function(x, name, value) stop("MainEventLoop cannot be modified", call. = FALSE)

#' @export
`[[<-.MainEventLoop` <- function(x, i, value) stop("MainEventLoop cannot be modified", call. = FALSE)

### associated functions for MainEventLoop



class(`MainEventLoop`) <- "MainEventLoop__bundle"

#' @export
`print.MainEventLoop__bundle` <- function(x, ...) {
  cat('MainEventLoop')
}

#' @export
`$<-.MainEventLoop__bundle` <- function(x, name, value) stop("MainEventLoop cannot be modified", call. = FALSE)

#' @export
`[[<-.MainEventLoop__bundle` <- function(x, i, value) stop("MainEventLoop cannot be modified", call. = FALSE)

### wrapper functions for WindowController

`WindowController_open_window` <- function(self) {
  function(`title`) {
    invisible(.Call(savvy_WindowController_open_window__impl, `self`, `title`))
  }
}

`WindowController_close_window` <- function(self) {
  function() {
    invisible(.Call(savvy_WindowController_close_window__impl, `self`))
  }
}

`.savvy_wrap_WindowController` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`open_window` <- `WindowController_open_window`(ptr)
  e$`close_window` <- `WindowController_close_window`(ptr)

  class(e) <- "WindowController"
  e
}

#' @export
`$<-.WindowController` <- function(x, name, value) stop("WindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.WindowController` <- function(x, i, value) stop("WindowController cannot be modified", call. = FALSE)



`WindowController` <- new.env(parent = emptyenv())

#' @export
`$<-.WindowController` <- function(x, name, value) stop("WindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.WindowController` <- function(x, i, value) stop("WindowController cannot be modified", call. = FALSE)

### associated functions for WindowController

`WindowController`$`new` <- function() {
  .savvy_wrap_WindowController(.Call(savvy_WindowController_new__impl))
}


class(`WindowController`) <- "WindowController__bundle"

#' @export
`print.WindowController__bundle` <- function(x, ...) {
  cat('WindowController')
}

#' @export
`$<-.WindowController__bundle` <- function(x, name, value) stop("WindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.WindowController__bundle` <- function(x, i, value) stop("WindowController cannot be modified", call. = FALSE)

