# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib winitPumpRPackage, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}


`foo` <- function() {
  invisible(.Call(savvy_foo__impl))
}


`foo2` <- function() {
  .savvy_wrap_Foo2(.Call(savvy_foo2__impl))
}

### wrapper functions for AppController

`AppController_resize` <- function(self) {
  function(`width`, `height`) {
    invisible(.Call(savvy_AppController_resize__impl, `self`, `width`, `height`))
  }
}

`AppController_close` <- function(self) {
  function() {
    invisible(.Call(savvy_AppController_close__impl, `self`))
  }
}

`.savvy_wrap_AppController` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`resize` <- `AppController_resize`(ptr)
  e$`close` <- `AppController_close`(ptr)

  class(e) <- "AppController"
  e
}

#' @export
`$<-.AppController` <- function(x, name, value) stop("AppController cannot be modified", call. = FALSE)

#' @export
`[[<-.AppController` <- function(x, i, value) stop("AppController cannot be modified", call. = FALSE)



`AppController` <- new.env(parent = emptyenv())

#' @export
`$<-.AppController` <- function(x, name, value) stop("AppController cannot be modified", call. = FALSE)

#' @export
`[[<-.AppController` <- function(x, i, value) stop("AppController cannot be modified", call. = FALSE)

### associated functions for AppController

`AppController`$`new` <- function() {
  .savvy_wrap_AppController(.Call(savvy_AppController_new__impl))
}


class(`AppController`) <- "AppController__bundle"

#' @export
`print.AppController__bundle` <- function(x, ...) {
  cat('AppController')
}

#' @export
`$<-.AppController__bundle` <- function(x, name, value) stop("AppController cannot be modified", call. = FALSE)

#' @export
`[[<-.AppController__bundle` <- function(x, i, value) stop("AppController cannot be modified", call. = FALSE)

### wrapper functions for Foo2


`.savvy_wrap_Foo2` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- "Foo2"
  e
}

#' @export
`$<-.Foo2` <- function(x, name, value) stop("Foo2 cannot be modified", call. = FALSE)

#' @export
`[[<-.Foo2` <- function(x, i, value) stop("Foo2 cannot be modified", call. = FALSE)



`Foo2` <- new.env(parent = emptyenv())

#' @export
`$<-.Foo2` <- function(x, name, value) stop("Foo2 cannot be modified", call. = FALSE)

#' @export
`[[<-.Foo2` <- function(x, i, value) stop("Foo2 cannot be modified", call. = FALSE)

### associated functions for Foo2



class(`Foo2`) <- "Foo2__bundle"

#' @export
`print.Foo2__bundle` <- function(x, ...) {
  cat('Foo2')
}

#' @export
`$<-.Foo2__bundle` <- function(x, name, value) stop("Foo2 cannot be modified", call. = FALSE)

#' @export
`[[<-.Foo2__bundle` <- function(x, i, value) stop("Foo2 cannot be modified", call. = FALSE)

