# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib winitRpackage, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}


### wrapper functions for ExternalWindowController

`ExternalWindowController_open_window` <- function(self) {
  function(`title`) {
    invisible(.Call(savvy_ExternalWindowController_open_window__impl, `self`, `title`))
  }
}

`ExternalWindowController_close_window` <- function(self) {
  function() {
    invisible(.Call(savvy_ExternalWindowController_close_window__impl, `self`))
  }
}

`.savvy_wrap_ExternalWindowController` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`open_window` <- `ExternalWindowController_open_window`(ptr)
  e$`close_window` <- `ExternalWindowController_close_window`(ptr)

  class(e) <- "ExternalWindowController"
  e
}

#' @export
`$<-.ExternalWindowController` <- function(x, name, value) stop("ExternalWindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.ExternalWindowController` <- function(x, i, value) stop("ExternalWindowController cannot be modified", call. = FALSE)



`ExternalWindowController` <- new.env(parent = emptyenv())

#' @export
`$<-.ExternalWindowController` <- function(x, name, value) stop("ExternalWindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.ExternalWindowController` <- function(x, i, value) stop("ExternalWindowController cannot be modified", call. = FALSE)

### associated functions for ExternalWindowController

`ExternalWindowController`$`new` <- function() {
  .savvy_wrap_ExternalWindowController(.Call(savvy_ExternalWindowController_new__impl))
}


class(`ExternalWindowController`) <- "ExternalWindowController__bundle"

#' @export
`print.ExternalWindowController__bundle` <- function(x, ...) {
  cat('ExternalWindowController')
}

#' @export
`$<-.ExternalWindowController__bundle` <- function(x, name, value) stop("ExternalWindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.ExternalWindowController__bundle` <- function(x, i, value) stop("ExternalWindowController cannot be modified", call. = FALSE)

### wrapper functions for SpawnedWindowController

`SpawnedWindowController_open_window` <- function(self) {
  function(`title`) {
    invisible(.Call(savvy_SpawnedWindowController_open_window__impl, `self`, `title`))
  }
}

`SpawnedWindowController_close_window` <- function(self) {
  function() {
    invisible(.Call(savvy_SpawnedWindowController_close_window__impl, `self`))
  }
}

`.savvy_wrap_SpawnedWindowController` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`open_window` <- `SpawnedWindowController_open_window`(ptr)
  e$`close_window` <- `SpawnedWindowController_close_window`(ptr)

  class(e) <- "SpawnedWindowController"
  e
}

#' @export
`$<-.SpawnedWindowController` <- function(x, name, value) stop("SpawnedWindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.SpawnedWindowController` <- function(x, i, value) stop("SpawnedWindowController cannot be modified", call. = FALSE)



`SpawnedWindowController` <- new.env(parent = emptyenv())

#' @export
`$<-.SpawnedWindowController` <- function(x, name, value) stop("SpawnedWindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.SpawnedWindowController` <- function(x, i, value) stop("SpawnedWindowController cannot be modified", call. = FALSE)

### associated functions for SpawnedWindowController

`SpawnedWindowController`$`new` <- function() {
  .savvy_wrap_SpawnedWindowController(.Call(savvy_SpawnedWindowController_new__impl))
}


class(`SpawnedWindowController`) <- "SpawnedWindowController__bundle"

#' @export
`print.SpawnedWindowController__bundle` <- function(x, ...) {
  cat('SpawnedWindowController')
}

#' @export
`$<-.SpawnedWindowController__bundle` <- function(x, name, value) stop("SpawnedWindowController cannot be modified", call. = FALSE)

#' @export
`[[<-.SpawnedWindowController__bundle` <- function(x, i, value) stop("SpawnedWindowController cannot be modified", call. = FALSE)

